---
- hosts: update
  remote_user: root
  tasks:
  - name: upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 600
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
