---
- name: change password
  hosts: test
  remote_user: root
  vars_prompt:
  - name: "Username"
    prompt: "Enter username for password change"

  tasks:
  - name: Check if username exists
    shell: id -u "{{Username}}"
    register: user_exists

  - name: change password
    user:
      name: "{{Username}}"
      password: ""
      update_password: always
